[package]
name = "le"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
prettytable = "0.10.0"

[build-dependencies]
lalrpop = "0.22.2"
